// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAskB23xsNqNRLJDYBwv3hjYfhsN2DiTiQ',
    appId: '1:241034941249:web:9f5e47aafe0faa677687c0',
    messagingSenderId: '241034941249',
    projectId: 'calculator-app-33d19',
    authDomain: 'calculator-app-33d19.firebaseapp.com',
    storageBucket: 'calculator-app-33d19.firebasestorage.app',
    measurementId: 'G-GJDHKRQCR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS14M1xvQXgRXesNJckTcQfsuKwSwPaB0',
    appId: '1:241034941249:android:8729f142c4e64a577687c0',
    messagingSenderId: '241034941249',
    projectId: 'calculator-app-33d19',
    storageBucket: 'calculator-app-33d19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqnxsuICFKDF-kU42tp28GLOxl8Kmv9G4',
    appId: '1:241034941249:ios:86749ee2c61fba887687c0',
    messagingSenderId: '241034941249',
    projectId: 'calculator-app-33d19',
    storageBucket: 'calculator-app-33d19.firebasestorage.app',
    iosBundleId: 'com.example.calculatorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqnxsuICFKDF-kU42tp28GLOxl8Kmv9G4',
    appId: '1:241034941249:ios:86749ee2c61fba887687c0',
    messagingSenderId: '241034941249',
    projectId: 'calculator-app-33d19',
    storageBucket: 'calculator-app-33d19.firebasestorage.app',
    iosBundleId: 'com.example.calculatorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAskB23xsNqNRLJDYBwv3hjYfhsN2DiTiQ',
    appId: '1:241034941249:web:89eb81d9e82b7c367687c0',
    messagingSenderId: '241034941249',
    projectId: 'calculator-app-33d19',
    authDomain: 'calculator-app-33d19.firebaseapp.com',
    storageBucket: 'calculator-app-33d19.firebasestorage.app',
    measurementId: 'G-KDY9NHF3DM',
  );
}
